-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 17:46:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd1_ind_automotriz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd1_ind_automotriz` ;

-- -----------------------------------------------------
-- Schema bd1_ind_automotriz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd1_ind_automotriz` DEFAULT CHARACTER SET utf8 ;
USE `bd1_ind_automotriz` ;

-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`insumo` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`insumo` (
  `insumo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`insumo_id`),
  UNIQUE INDEX `InsumosID_UNIQUE` (`insumo_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`pais` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`pais` (
  `pais_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_iso` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`pais_id`),
  UNIQUE INDEX `pais_id_UNIQUE` (`pais_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`provincia` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`provincia` (
  `provincia_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais_pais_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`provincia_id`, `pais_pais_id`),
  UNIQUE INDEX `provincia_id_UNIQUE` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_provincia_pais1_idx` (`pais_pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_provincia_pais1`
    FOREIGN KEY (`pais_pais_id`)
    REFERENCES `bd1_ind_automotriz`.`pais` (`pais_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`ciudad` (
  `ciudad_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `provincia_provincia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ciudad_id`, `provincia_provincia_id`),
  UNIQUE INDEX `ciudad_id_UNIQUE` (`ciudad_id` ASC) VISIBLE,
  INDEX `fk_ciudad_provincia1_idx` (`provincia_provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_provincia1`
    FOREIGN KEY (`provincia_provincia_id`)
    REFERENCES `bd1_ind_automotriz`.`provincia` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`direccion` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`direccion` (
  `direccion_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `ciudad_ciudad_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`direccion_id`, `ciudad_ciudad_id`),
  INDEX `fk_direccion_ciudad1_idx` (`ciudad_ciudad_id` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_ciudad1`
    FOREIGN KEY (`ciudad_ciudad_id`)
    REFERENCES `bd1_ind_automotriz`.`ciudad` (`ciudad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`proveedor` (
  `proveedor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion_direccion_id` INT UNSIGNED NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`proveedor_id`, `direccion_direccion_id`),
  UNIQUE INDEX `ProveedoresID_UNIQUE` (`proveedor_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_proveedor_direccion1_idx` (`direccion_direccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_direccion1`
    FOREIGN KEY (`direccion_direccion_id`)
    REFERENCES `bd1_ind_automotriz`.`direccion` (`direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`compra` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`compra` (
  `numero_compra` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `proveedor_proveedor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_compra`, `proveedor_proveedor_id`),
  UNIQUE INDEX `CompraID_UNIQUE` (`numero_compra` ASC) VISIBLE,
  INDEX `fk_compra_proveedor1_idx` (`proveedor_proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor_proveedor_id`)
    REFERENCES `bd1_ind_automotriz`.`proveedor` (`proveedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`detalle_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`detalle_compra` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`detalle_compra` (
  `compra_numero_compra` INT UNSIGNED NOT NULL,
  `insumo_insumo_id` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`compra_numero_compra`, `insumo_insumo_id`),
  INDEX `fk_compra_has_insumo_insumo1_idx` (`insumo_insumo_id` ASC) VISIBLE,
  INDEX `fk_compra_has_insumo_compra_idx` (`compra_numero_compra` ASC) VISIBLE,
  CONSTRAINT `fk_compra_has_insumo_compra`
    FOREIGN KEY (`compra_numero_compra`)
    REFERENCES `bd1_ind_automotriz`.`compra` (`numero_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_has_insumo_insumo1`
    FOREIGN KEY (`insumo_insumo_id`)
    REFERENCES `bd1_ind_automotriz`.`insumo` (`insumo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`concesionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`concesionario` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`concesionario` (
  `concesionario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion_direccion_id` INT UNSIGNED NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`concesionario_id`, `direccion_direccion_id`),
  UNIQUE INDEX `concesionario_id_UNIQUE` (`concesionario_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_concesionario_direccion1_idx` (`direccion_direccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_concesionario_direccion1`
    FOREIGN KEY (`direccion_direccion_id`)
    REFERENCES `bd1_ind_automotriz`.`direccion` (`direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`pedido` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`pedido` (
  `pedido_id` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `concesionario_concesionario_id` INT UNSIGNED NOT NULL,
  `fecha_entrega_estimada` DATETIME NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`pedido_id`),
  UNIQUE INDEX `pedido_id_UNIQUE` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_pedido_concesionario1_idx` (`concesionario_concesionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_concesionario1`
    FOREIGN KEY (`concesionario_concesionario_id`)
    REFERENCES `bd1_ind_automotriz`.`concesionario` (`concesionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`marca` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`marca` (
  `marca_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `iso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`marca_id`),
  UNIQUE INDEX `marca_id_UNIQUE` (`marca_id` ASC) VISIBLE,
  UNIQUE INDEX `iso_UNIQUE` (`iso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`modelo` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`modelo` (
  `modelo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `marca_marca_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `iso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`modelo_id`, `marca_marca_id`),
  UNIQUE INDEX `modelo_id_UNIQUE` (`modelo_id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_modelo_marca1_idx` (`marca_marca_id` ASC) VISIBLE,
  UNIQUE INDEX `iso_UNIQUE` (`iso` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_marca_id`)
    REFERENCES `bd1_ind_automotriz`.`marca` (`marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`detalle_pedido` (
  `pedido_pedido_id` INT UNSIGNED NOT NULL,
  `modelo_modelo_id` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `baja` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`pedido_pedido_id`, `modelo_modelo_id`),
  INDEX `fk_pedido_has_modelo_modelo1_idx` (`modelo_modelo_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_modelo_pedido1_idx` (`pedido_pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_modelo_pedido1`
    FOREIGN KEY (`pedido_pedido_id`)
    REFERENCES `bd1_ind_automotriz`.`pedido` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_modelo_modelo1`
    FOREIGN KEY (`modelo_modelo_id`)
    REFERENCES `bd1_ind_automotriz`.`modelo` (`modelo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`linea_montaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`linea_montaje` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`linea_montaje` (
  `linea_montaje_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modelo_modelo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`linea_montaje_id`, `modelo_modelo_id`),
  UNIQUE INDEX `linea_montaje_id_UNIQUE` (`linea_montaje_id` ASC) VISIBLE,
  INDEX `fk_linea_montaje_modelo1_idx` (`modelo_modelo_id` ASC) VISIBLE,
  CONSTRAINT `fk_linea_montaje_modelo1`
    FOREIGN KEY (`modelo_modelo_id`)
    REFERENCES `bd1_ind_automotriz`.`modelo` (`modelo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`tarea` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`tarea` (
  `tarea_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(200) NULL,
  PRIMARY KEY (`tarea_id`),
  UNIQUE INDEX `tarea_id_UNIQUE` (`tarea_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`estacion` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`estacion` (
  `estacion_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orden` INT NOT NULL,
  `linea_montaje_linea_montaje_id` INT UNSIGNED NOT NULL,
  `tarea_tarea_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`estacion_id`, `linea_montaje_linea_montaje_id`),
  UNIQUE INDEX `estacion_id_UNIQUE` (`estacion_id` ASC) VISIBLE,
  INDEX `fk_estacion_linea_montaje1_idx` (`linea_montaje_linea_montaje_id` ASC) VISIBLE,
  INDEX `fk_estacion_tarea1_idx` (`tarea_tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_estacion_linea_montaje1`
    FOREIGN KEY (`linea_montaje_linea_montaje_id`)
    REFERENCES `bd1_ind_automotriz`.`linea_montaje` (`linea_montaje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_tarea1`
    FOREIGN KEY (`tarea_tarea_id`)
    REFERENCES `bd1_ind_automotriz`.`tarea` (`tarea_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`tarea_consume_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`tarea_consume_insumo` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`tarea_consume_insumo` (
  `tarea_tarea_id` INT UNSIGNED NOT NULL,
  `insumo_insumo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tarea_tarea_id`, `insumo_insumo_id`),
  INDEX `fk_tarea_has_insumo_insumo1_idx` (`insumo_insumo_id` ASC) VISIBLE,
  INDEX `fk_tarea_has_insumo_tarea1_idx` (`tarea_tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_has_insumo_tarea1`
    FOREIGN KEY (`tarea_tarea_id`)
    REFERENCES `bd1_ind_automotriz`.`tarea` (`tarea_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_has_insumo_insumo1`
    FOREIGN KEY (`insumo_insumo_id`)
    REFERENCES `bd1_ind_automotriz`.`insumo` (`insumo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`vehiculo` (
  `vehiculo_id` INT NOT NULL AUTO_INCREMENT,
  `nro_chasis` VARCHAR(45) NOT NULL,
  `modelo_modelo_id` INT UNSIGNED NOT NULL,
  `pedido_pedido_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vehiculo_id`, `modelo_modelo_id`, `pedido_pedido_id`),
  UNIQUE INDEX `vehiculo_id_UNIQUE` (`vehiculo_id` ASC) VISIBLE,
  INDEX `fk_vehiculo_pedido1_idx` (`pedido_pedido_id` ASC) VISIBLE,
  INDEX `fk_vehiculo_modelo1_idx` (`modelo_modelo_id` ASC) VISIBLE,
  UNIQUE INDEX `nro_chasis_UNIQUE` (`nro_chasis` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_pedido1`
    FOREIGN KEY (`pedido_pedido_id`)
    REFERENCES `bd1_ind_automotriz`.`pedido` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_modelo1`
    FOREIGN KEY (`modelo_modelo_id`)
    REFERENCES `bd1_ind_automotriz`.`modelo` (`modelo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd1_ind_automotriz`.`vehiculo_en_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd1_ind_automotriz`.`vehiculo_en_estacion` ;

CREATE TABLE IF NOT EXISTS `bd1_ind_automotriz`.`vehiculo_en_estacion` (
  `vehiculo_vehiculo_id` INT NOT NULL,
  `estacion_estacion_id` INT UNSIGNED NOT NULL,
  `fecha_hora_ingreso` DATETIME NOT NULL,
  `fecha_hora_egreso` DATETIME NULL,
  PRIMARY KEY (`vehiculo_vehiculo_id`, `estacion_estacion_id`),
  INDEX `fk_vehiculo_has_estacion_estacion1_idx` (`estacion_estacion_id` ASC) VISIBLE,
  INDEX `fk_vehiculo_en_estacion_vehiculo1_idx` (`vehiculo_vehiculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_has_estacion_estacion1`
    FOREIGN KEY (`estacion_estacion_id`)
    REFERENCES `bd1_ind_automotriz`.`estacion` (`estacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_en_estacion_vehiculo1`
    FOREIGN KEY (`vehiculo_vehiculo_id`)
    REFERENCES `bd1_ind_automotriz`.`vehiculo` (`vehiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
